site_name: Squad SDK Documentation
theme:
  name: material
nav:
  - Home: index.md
  - iOS:
      - Overview: ios/getting-started.md
      - SDK Init: ios/sdk-init.md
      - User Auth: ios/user-auth.md
      - WebView Events: ios/webview-events.md
      - Troubleshooting: ios/troubleshooting.md
  - Android:
      - Overview: android/getting-started.md
  - React Native:
      - Overview: react-native/getting-started.md
