site_name: Squad SDK Documentation
theme:
  name: material
nav:
  - Home: index.md
  - iOS:
      - Overview: ios/getting-started.md
  - Android:
      - Overview: android/getting-started.md
  - React Native:
      - Overview: react-native/getting-started.md
