site_name: Squad SDK Documentation
docs_dir: "."
theme:
  name: material
nav:
  - Home: index.md
  - iOS: ios/getting-started.md
  - Android: android/getting-started.md
  - React Native: react-native/getting-started.md
